# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XPYWUHQbVBZ9E-iHKgjDDRh3AE9RfLFE
"""

import pandas as pd
from math import floor
from datetime import datetime

loyalty_rules_path = 'loyalty_rules.csv'
sales_header_path = 'sales_header.csv'
sales_line_items_path = 'sales_line_items.csv'
customers_path = '/customers_2000.csv'

try:
    lr = pd.read_csv(loyalty_rules_path)
    spend_per_point = float(lr.iloc[0].get('spend_per_point', 100))
    points_per_spend = float(lr.iloc[0].get('points_per_spend', 1))
except Exception:
    spend_per_point = 100.0
    points_per_spend = 1.0

try:
    sh = pd.read_csv(sales_header_path)
except Exception:
    sh = pd.DataFrame()

try:
    sl = pd.read_csv(sales_line_items_path)
except Exception:
    sl = pd.DataFrame()

if 'transaction_amount' in sh.columns:
    sh['transaction_amount'] = sh['transaction_amount'].fillna(0)
elif 'sale_amount' in sh.columns:
    sh['transaction_amount'] = sh['sale_amount'].fillna(0)
else:
    if not sl.empty and {'sale_id','quantity','unit_price'}.issubset(sl.columns):
        totals = sl.copy()
        totals['line_total'] = totals['quantity'] * totals['unit_price']
        totals = totals.groupby('sale_id', as_index=False)['line_total'].sum().rename(columns={'line_total':'transaction_amount'})
        if 'sale_id' in sh.columns:
            sh = sh.merge(totals, on='sale_id', how='left')
        else:
            sh = totals
    elif not sl.empty and {'sale_id','amount'}.issubset(sl.columns):
        totals = sl.groupby('sale_id', as_index=False)['amount'].sum().rename(columns={'amount':'transaction_amount'})
        if 'sale_id' in sh.columns:
            sh = sh.merge(totals, on='sale_id', how='left')
        else:
            sh = totals

if 'sale_date' in sh.columns:
    sh['sale_date'] = pd.to_datetime(sh['sale_date'], errors='coerce')

if 'sale_id' not in sh.columns:
    sh = sh.reset_index().rename(columns={'index':'sale_id'})

sh['transaction_amount'] = sh.get('transaction_amount', pd.Series(0, index=sh.index)).fillna(0)
sh['accrued_points'] = (sh['transaction_amount'] // spend_per_point) * points_per_spend
sh.to_csv('transaction_points.csv', index=False)

try:
    customers = pd.read_csv(customers_path)
except Exception:
    customers = pd.DataFrame(columns=['customer_id','first_name','email','loyalty_status','total_loyalty_points'])

if 'customer_id' not in customers.columns:
    customers = customers.reset_index().rename(columns={'index':'customer_id'})

if 'total_loyalty_points' not in customers.columns:
    customers['total_loyalty_points'] = 0

points = sh.groupby('customer_id', as_index=False)['accrued_points'].sum().rename(columns={'accrued_points':'new_points'})
if 'customer_id' in points.columns:
    customers = customers.merge(points, on='customer_id', how='left')
else:
    customers['new_points'] = 0

customers['new_points'] = customers.get('new_points', 0).fillna(0)
customers['total_loyalty_points'] = customers['total_loyalty_points'].fillna(0) + customers['new_points']
customers = customers.drop(columns=['new_points'], errors='ignore')
customers.to_csv('customers_updated.csv', index=False)

sales = sh.copy()
if sales.empty and not sl.empty:
    if 'customer_id' in sl.columns:
        sales = sl.groupby('sale_id', as_index=False).agg({'customer_id':'first','amount':'sum'}).rename(columns={'amount':'transaction_amount'})

if not sales.empty:
    if 'sale_date' in sales.columns:
        max_date = sales['sale_date'].max()
    else:
        max_date = pd.to_datetime('today')
    if 'sale_id' in sales.columns:
        freq_agg = ('sale_id','nunique')
    else:
        freq_agg = ('transaction_amount','count')
    rfm = sales.groupby('customer_id', as_index=False).agg(last_purchase=('sale_date', lambda x: x.max() if 'sale_date' in sales.columns else pd.NaT),
                                                          frequency=freq_agg,
                                                          monetary=('transaction_amount','sum'))
    if 'last_purchase' in rfm.columns:
        rfm['recency_days'] = (pd.to_datetime(max_date) - pd.to_datetime(rfm['last_purchase'], errors='coerce')).dt.days
    else:
        rfm['recency_days'] = None
else:
    rfm = pd.DataFrame(columns=['customer_id','recency_days','frequency','monetary'])

rfm = rfm.merge(customers[['customer_id','total_loyalty_points']], on='customer_id', how='left')
rfm['total_loyalty_points'] = rfm['total_loyalty_points'].fillna(0)
rfm.to_csv('rfm_metrics.csv', index=False)

if not rfm.empty:
    threshold = rfm['monetary'].quantile(0.9)
    rfm['segment'] = ''
    rfm.loc[rfm['monetary'] >= threshold, 'segment'] = 'High-Spenders'
    rfm.loc[(rfm['recency_days'] > 30) & (rfm['total_loyalty_points'] > 0) & (rfm['segment'] == ''), 'segment'] = 'At-Risk'
else:
    rfm['segment'] = ''

rfm.to_csv('customers_segments.csv', index=False)



